" Don't try to be vi compatible 
" We want the latest Vim settings/options.
set nocompatible
filetype off

execute pathogen#infect()
filetype plugin indent on

syntax enable
" Make backspace behave like every other editor.
set backspace=indent,eol,start
" The default is \, but a comma is much better.
let mapleader = ','
" Let's activate line numbers.
set number
set ruler
" No damn bells!
set noerrorbells visualbell t_vb=
" Automatically write the file when switching buffers.
set autowriteall
" Set our desired autocompletion matching.
set complete=.,w,b,u 
set modelines=0
set encoding=utf-8

" Whitespace
set wrap
set textwidth=79
set formatoptions=tcqrn1
set tabstop=8
set shiftwidth=4
set softtabstop=4
set expandtab
set noshiftround

" Swap files out of the project root
set backupdir=~/.vim/backup/
set directory=~/.vim/swap/

" Cursor motion
set scrolloff=3
set matchpairs+=<:> " use % to jump between pairs
runtime! macros/matchit.vim

" Move up/down editor lines
nnoremap j gj
nnoremap k gk
nnoremap gj j
nnoremap gk k
" ESC with jj
inoremap jj <Esc>

" Allow hidden buffers
set hidden
set ttyfast
set laststatus=2
set showmode
set showcmd



"---------------Visuals---------------"
set background=dark
colorscheme material-theme
" Use 256 colors. This is useful for Terminal Vim.
set t_Co=256
" Set the default font family and size.
set guifont=Fira\ Code\ Retina:h17
" We want pretty symbols, when available.
set macligatures
" We don't want Gui tabs.
set guioptions-=e
"Macvim-specific line-height.
set linespace=16

let g:solarized_termcolors=256
let g:solarized_termtrans=1

"Disable Gui scrollbars.
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R

" Hide scroll bars in macvim
set guioptions=




"---------------Search---------------"
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
map <leader><space> :let @/=''<cr> " clear search




"---------------Mappings---------------"
" Remap help key.
inoremap <F1> <ESC>:set invfullscreen<CR>a
nnoremap <F1> :set invfullscreen<CR>
vnoremap <F1> :set invfullscreen<CR>

" Textmate holdouts

" Formatting
map <leader>q gqip

" Visualize tabs and newlines
set listchars=tab:▸\ ,eol:¬
" Uncomment this to enable by default:
" set list " To enable by default
" Or use your leader key + l to toggle on/off
map <leader>l :set list!<CR> " Toggle tabs and EOL

" Ctrl+n will close the nerdtree
map <C-n> :NERDTreeToggle<CR>
" close vim if the only window left open is a NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" arrows baby
let g:NERDTreeDirArrowExpandable = '⇀'
let g:NERDTreeDirArrowCollapsible = '⇂'

" Enable folding
set foldmethod=indent
set foldlevel=99

" map tab nav
map <C-t><up> :tabr<cr>
map <C-t><down> :tabl<cr>
map <C-t><left> :tabp<cr>
map <C-t><right> :tabn<cr>

" Custom Key Mapped
" space to fold the code
nnoremap <space> za



"-------------Split Management--------------"
" Make splits default to below...
set splitbelow
" And to the right. This feels more natural.
set splitright

"We'll set simpler mappings to switch between splits.
nmap <C-J> <C-W><C-J>
nmap <C-K> <C-W><C-K>
nmap <C-H> <C-W><C-H>
nmap <C-L> <C-W><C-L>




"-------------Auto-Commands--------------"
" Automatically source the Vimrc file on save.

augroup autosourcing
	autocmd!
	autocmd BufWritePost .vimrc source %
augroup END
